version: "3"

services:
  api:
    ports:
      - 81:8080

  web:
    build:
      dockerfile: develop.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ${WEB_ABSOLUTE_PATH}:/dev/app
      - dev/app/node_modules
    environment:
      - NODE_ENV=development

  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
