version: "3"

services:
  api:
    ports:
      - 81:8080

  web:
    build:
      dockerfile: develop.dockerfile
    ports:
      - 3000:3000
    volumes:
      - web-artifacts:/app
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
volumes:
  web-artifacts:
    driver: local
    driver_opts:
      type: none
      device: ${WEB_ABSOLUTE_PATH}
      o: bind
