version: '3'

services:
  api:
    build: ./Api/
    environment:
      - ASPNETCORE_HTTPS_PORT=${API_HTTPS_PORT}
      - ASPNETCORE_URLS=${API_URLS}
  web:
    build: ./Web/
    volumes:
      - web-artifacts:/app/build
  # web:
  #   build: ./Web/

  # db:
  #   build: ./Db/

  # nginx: 
  #   build: ./Nginx/
volumes:
  web-artifacts: