version: "3"

services:
  api:
    build: ${SRC_API_RELATIVE_PATH}
    environment:
      - ASPNETCORE_HTTPS_PORT=${API_HTTPS_PORT}
      - ASPNETCORE_URLS=${API_URLS}

  web:
    build: ${SRC_WEB_RELATIVE_PATH}
    volumes:
      - web-artifacts:/app/build
    environment:
      - API_ENDPOINT=${API_ALIAS}:${API_PORT}

  db:
    build: ./Db/

  nginx:
    build: ./Nginx/
    ports:
      - 80:80
    volumes:
      - web-artifacts:/static:ro
    depends_on:
      - web
      - api
volumes:
  web-artifacts:
