version: "3"

services:
  api:
    build: ../Scheduler.API
    container_name: sc_api
    environment:
      - ASPNETCORE_HTTPS_PORT=44310
      - ASPNETCORE_URLS=https://+:443;http://+:8080
    depends_on:
      - db

  web:
    build: ../Scheduler.WEB
    container_name: sc_web
    volumes:
      - web-artifacts:/app/build
    environment:
      - API_ENDPOINT=api:8080

  db:
    build: ./Db/
    container_name: sc_db

  nginx:
    build: ./Nginx/
    container_name: sc_nginx
    ports:
      - 80:80
    volumes:
      - web-artifacts:/static:ro
    depends_on:
      - web
      - api
volumes:
  web-artifacts:
