version: "3"

services:
  nginx:
    build:
      dockerfile: develop.dockerfile

  api:
    ports:
      - 81:8080

  web:
    build:
      dockerfile: develop.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ${FOLDER_ABSOLUTE_PATH}Scheduler.WEB:/develop/app
      - /develop/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
