version: '3'

services:
  api:
    build: ./Api/
    environment:
      - ASPNETCORE_HTTPS_PORT=${API_HTTPS_PORT}
      - ASPNETCORE_URLS=${API_URLS}
    ports:
      - 81:8080
  web:
    build: ./Web/
    volumes:
      - web-artifacts:/app
    environment:
      - API_ENDPOINT=${API_ALIAS}:${API_PORT}
    depends_on:
      - api
  # db:
  #   build: ./Db/
  nginx: 
    build: ./Nginx/
    ports:
      - 80:80
    volumes:
      - web-artifacts:/app
    depends_on:
      - web
volumes:
  web-artifacts: {}