INSERT INTO public.class_types (id, name) VALUES (1, 'Lection');
INSERT INTO public.class_types (id, name) VALUES (2, 'Laba');
INSERT INTO public.class_types (id, name) VALUES (3, 'Shared');
INSERT INTO public.classes (id, id_lesson, id_classroom, id_group, id_teacher, class_time_begin, id_class_type, day_number, class_time_end) VALUES (2, 1, 3, 2, 1, '11:40:00', 2, 1, '13:15:00');
INSERT INTO public.classrooms (id, name, description) VALUES (1, '1158', null);
INSERT INTO public.classrooms (id, name, description) VALUES (2, '1215', null);
INSERT INTO public.classrooms (id, name, description) VALUES (3, '5141', null);
INSERT INTO public.departments (id, name, description) VALUES (1, 'БЖД', 'Самая сука важная кафедра');
INSERT INTO public.departments (id, name, description) VALUES (2, 'ИС', null);
INSERT INTO public.departments (id, name, description) VALUES (3, 'АПУ', null);
INSERT INTO public.groups (id, id_department, name, group_type) VALUES (2, 2, '6374', 'Main');
INSERT INTO public.lesson_names (id, name) VALUES (1, 'Безопасность Жизнидеятельности');
INSERT INTO public.lesson_names (id, name) VALUES (2, 'Теория разработки программного обеспечения');
INSERT INTO public.lesson_names (id, name) VALUES (3, 'БЖД');
INSERT INTO public.lesson_names (id, name) VALUES (4, 'ТПРО');
INSERT INTO public.lesson_names_to_lessons (id_lesson, id_lesson_name) VALUES (1, 1);
INSERT INTO public.lesson_names_to_lessons (id_lesson, id_lesson_name) VALUES (1, 3);
INSERT INTO public.lesson_names_to_lessons (id_lesson, id_lesson_name) VALUES (2, 2);
INSERT INTO public.lesson_names_to_lessons (id_lesson, id_lesson_name) VALUES (2, 4);
INSERT INTO public.lessons (id, id_primary_name, id_department, description) VALUES (1, 1, 1, 'САМАЯСУКАВАЖНАЯПАРАВМИРЕ');
INSERT INTO public.lessons (id, id_primary_name, id_department, description) VALUES (2, 2, 2, '');
INSERT INTO public.users (id, name, surname, patronymic, phone, email, autorization_shit) VALUES (1, 'Овдиенко', 'Х', 'З', null, null, null);
INSERT INTO public.users_to_user_roles (id_user, id_group, id_department, role) VALUES (1, null, 1, 'Teacher');